services:
  pandalla-docs:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    environment:
      NODE_ENV: production
      PORT: 3001
      HOSTNAME: 0.0.0.0
    ports:
      - "10008:3000"
    restart: unless-stopped
